#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
#ifndef FTSDKCOREKIT_SWIFT_H
#define FTSDKCOREKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FTSDKCoreKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC12FTSDKCoreKit16AnalyticsConfigs")
@interface AnalyticsConfigs : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@class UIColor;
@class NSCoder;

IB_DESIGNABLE
SWIFT_CLASS("_TtC12FTSDKCoreKit8CheckBox")
@interface CheckBox : UIControl
@property (nonatomic) IBInspectable BOOL isSquare;
@property (nonatomic) IBInspectable CGFloat checkmarkLineWidth;
@property (nonatomic) IBInspectable CGFloat boxLineWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull unCheckedColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull checkedColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull markColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit10ConfigData")
@interface ConfigData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit14FTSDKTextField")
@interface FTSDKTextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;

SWIFT_CLASS("_TtC12FTSDKCoreKit15CustomTextField")
@interface CustomTextField : FTSDKTextField
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)prepareForInterfaceBuilder;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@end


@class FTSDKProfileData;
@class FTSDKAuthentication;
@class FTSDKPlayerInfo;
@class FTSDKUser;

SWIFT_CLASS("_TtC12FTSDKCoreKit12FTSDKAppData")
@interface FTSDKAppData : NSObject
@property (nonatomic, strong) FTSDKProfileData * _Nullable profile;
@property (nonatomic, strong) FTSDKAuthentication * _Nullable authentication;
@property (nonatomic, strong) FTSDKPlayerInfo * _Nullable playerInfo;
@property (nonatomic, readonly, strong) FTSDKUser * _Nullable user;
@property (nonatomic) BOOL isLoginSocial;
@property (nonatomic, readonly) BOOL isValidUser;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIApplication;
@class NSURL;
@class NSUserActivity;
@protocol UIUserActivityRestoring;
@protocol FTSDKTrackerProtocol;
enum FTSDKLanguage : NSInteger;

SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKAppDelegate")
@interface FTSDKAppDelegate : NSObject
+ (FTSDKAppDelegate * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
- (void)didFinishLaunching:(UIApplication * _Nonnull)application with:(NSDictionary<UIApplicationLaunchOptionsKey, id> * _Nullable)launchOptions;
- (BOOL)application:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nullable)options;
- (BOOL)application:(UIApplication * _Nonnull)application open:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation;
- (BOOL)continue:(NSUserActivity * _Nullable)userActivity restorationHandler:(void (^ _Nullable)(NSArray<id <UIUserActivityRestoring>> * _Nullable))restorationHandler;
- (void)invokeTracker:(id <FTSDKTrackerProtocol> _Nonnull)tracker;
- (FTSDKAppData * _Nonnull)getAppData SWIFT_WARN_UNUSED_RESULT;
- (void)setLanguage:(enum FTSDKLanguage)language;
- (void)loadConfigWithCompleted:(void (^ _Nullable)(void))completed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class FTSDKError;
@class MaintenanceConfigs;
@class FTSDKSignIn;

SWIFT_PROTOCOL("_TtP12FTSDKCoreKit17FTSDKAuthDelegate_")
@protocol FTSDKAuthDelegate
@optional
- (void)onFTSDKIsReady;
- (void)onFTSDKErrorWithError:(FTSDKError * _Nonnull)error;
- (void)onFIDMaintenanceWithConfig:(MaintenanceConfigs * _Nonnull)config;
- (void)onFIDLinkAccountSuggestionWithMessage:(NSString * _Nonnull)message;
- (void)didSignInSuccess:(FTSDKSignIn * _Nonnull)signIn didSignInFor:(FTSDKUser * _Nonnull)user withMethod:(NSString * _Nonnull)authType;
- (void)didSignInFail:(FTSDKSignIn * _Nonnull)signIn with:(FTSDKError * _Nonnull)error;
- (void)didSignUpSuccess:(FTSDKSignIn * _Nonnull)signIn didSignInFor:(FTSDKUser * _Nonnull)user withMethod:(NSString * _Nonnull)authType;
- (void)didSignUpFail:(FTSDKSignIn * _Nonnull)signIn with:(FTSDKError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit19FTSDKAuthentication")
@interface FTSDKAuthentication : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable accessToken;
@property (nonatomic, readonly, copy) NSString * _Nullable idToken;
@property (nonatomic, readonly, copy) NSString * _Nullable refreshToken;
@property (nonatomic, readonly, copy) NSString * _Nullable tokenType;
@property (nonatomic, readonly, copy) NSString * _Nullable scope;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit31FTSDKBaseCollectionReusableView")
@interface FTSDKBaseCollectionReusableView : UICollectionReusableView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionViewLayout;

SWIFT_CLASS("_TtC12FTSDKCoreKit23FTSDKBaseCollectionView")
@interface FTSDKBaseCollectionView : UICollectionView
- (nonnull instancetype)initWithFrame:(CGRect)frame collectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit27FTSDKBaseCollectionViewCell")
@interface FTSDKBaseCollectionViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit18FTSDKBaseTableView")
@interface FTSDKBaseTableView : UITableView
- (nonnull instancetype)initWithFrame:(CGRect)frame style:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit22FTSDKBaseTableViewCell")
@interface FTSDKBaseTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
@end

@class UIView;

SWIFT_CLASS("_TtC12FTSDKCoreKit26FTSDKBottomSheetController")
@interface FTSDKBottomSheetController : NSObject
- (FTSDKBottomSheetController * _Nonnull)showWithContext:(UIView * _Nullable)context completion:(void (^ _Nullable)(void))completion;
- (void)hide;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit13FTSDKCardData")
@interface FTSDKCardData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable id;
@property (nonatomic, readonly, copy) NSString * _Nullable birthDay;
@property (nonatomic, readonly, copy) NSString * _Nullable birthPlace;
@property (nonatomic, readonly, copy) NSString * _Nullable cardType;
@property (nonatomic, readonly, copy) NSString * _Nullable cardSubType;
@property (nonatomic, readonly, copy) NSString * _Nullable citizenId;
@property (nonatomic, readonly, copy) NSString * _Nullable codeNumber;
/// 0(unknown) || 1(Male) || 2(Female) || 3(Other)
@property (nonatomic, readonly, copy) NSString * _Nullable gender;
@property (nonatomic, readonly, copy) NSString * _Nullable issueDate;
@property (nonatomic, readonly, copy) NSString * _Nullable issuePlace;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable nationality;
@property (nonatomic, readonly, copy) NSString * _Nullable originLocation;
@property (nonatomic, readonly, copy) NSString * _Nullable passportNo;
@property (nonatomic, readonly, copy) NSString * _Nullable recentLocation;
@property (nonatomic, readonly, copy) NSString * _Nullable validDate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16MVPComponentView")
@interface MVPComponentView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit18FTSDKComponentView")
@interface FTSDKComponentView : MVPComponentView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ModuleConfig;
@class ThemeConfigs;
@class SDKPromotion;
enum FTSDKEnvironment : NSInteger;
enum FTSDKFlow : NSInteger;
@protocol FTSDKTheme;

SWIFT_CLASS("_TtC12FTSDKCoreKit11FTSDKConfig")
@interface FTSDKConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull clientId;)
+ (NSString * _Nonnull)clientId SWIFT_WARN_UNUSED_RESULT;
+ (void)setClientId:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable gameCode;)
+ (NSString * _Nullable)gameCode SWIFT_WARN_UNUSED_RESULT;
+ (void)setGameCode:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull partnerCode;)
+ (NSString * _Nonnull)partnerCode SWIFT_WARN_UNUSED_RESULT;
+ (void)setPartnerCode:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull paymentMethod;)
+ (NSString * _Nonnull)paymentMethod SWIFT_WARN_UNUSED_RESULT;
+ (void)setPaymentMethod:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable bundleId;)
+ (NSString * _Nullable)bundleId SWIFT_WARN_UNUSED_RESULT;
+ (void)setBundleId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull redirectURI;)
+ (NSString * _Nonnull)redirectURI SWIFT_WARN_UNUSED_RESULT;
+ (void)setRedirectURI:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nonnull scopes;)
+ (NSArray<NSString *> * _Nonnull)scopes SWIFT_WARN_UNUSED_RESULT;
+ (void)setScopes:(NSArray<NSString *> * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull sentryDSN;)
+ (NSString * _Nonnull)sentryDSN SWIFT_WARN_UNUSED_RESULT;
+ (void)setSentryDSN:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable analyticKey;)
+ (NSString * _Nullable)analyticKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setAnalyticKey:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull appName;)
+ (NSString * _Nonnull)appName SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull domain;)
+ (NSString * _Nonnull)domain SWIFT_WARN_UNUSED_RESULT;
+ (void)setDomain:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull domainGame;)
+ (NSString * _Nonnull)domainGame SWIFT_WARN_UNUSED_RESULT;
+ (void)setDomainGame:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull domainWidget;)
+ (NSString * _Nonnull)domainWidget SWIFT_WARN_UNUSED_RESULT;
+ (void)setDomainWidget:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull configFileName;)
+ (NSString * _Nonnull)configFileName SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfigFileName:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable releaseVersionNumber;)
+ (NSString * _Nullable)releaseVersionNumber SWIFT_WARN_UNUSED_RESULT;
+ (void)setReleaseVersionNumber:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull projectFirebase;)
+ (NSString * _Nonnull)projectFirebase SWIFT_WARN_UNUSED_RESULT;
+ (void)setProjectFirebase:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable facebookAppID;)
+ (NSString * _Nullable)facebookAppID SWIFT_WARN_UNUSED_RESULT;
+ (void)setFacebookAppID:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable facebookClientID;)
+ (NSString * _Nullable)facebookClientID SWIFT_WARN_UNUSED_RESULT;
+ (void)setFacebookClientID:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<ModuleConfig *> * _Nullable modulesConfigs;)
+ (NSArray<ModuleConfig *> * _Nullable)modulesConfigs SWIFT_WARN_UNUSED_RESULT;
+ (void)setModulesConfigs:(NSArray<ModuleConfig *> * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) ThemeConfigs * _Nullable themeConfigs;)
+ (ThemeConfigs * _Nullable)themeConfigs SWIFT_WARN_UNUSED_RESULT;
+ (void)setThemeConfigs:(ThemeConfigs * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<SDKPromotion *> * _Nullable promotions;)
+ (NSArray<SDKPromotion *> * _Nullable)promotions SWIFT_WARN_UNUSED_RESULT;
+ (void)setPromotions:(NSArray<SDKPromotion *> * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL disableAllDialogLoading;)
+ (BOOL)disableAllDialogLoading SWIFT_WARN_UNUSED_RESULT;
+ (void)setDisableAllDialogLoading:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL disableAllHeaderMessage;)
+ (BOOL)disableAllHeaderMessage SWIFT_WARN_UNUSED_RESULT;
+ (void)setDisableAllHeaderMessage:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum FTSDKEnvironment env;)
+ (enum FTSDKEnvironment)env SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnv:(enum FTSDKEnvironment)value;
+ (void)setSDKLicenseWithLicense:(NSString * _Nonnull)license;
+ (void)setFPaySecretKey:(NSString * _Nonnull)secret;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum FTSDKFlow flow;)
+ (enum FTSDKFlow)flow SWIFT_WARN_UNUSED_RESULT;
+ (void)setFlow:(enum FTSDKFlow)value;
+ (void)setFlowDialog;
+ (void)setFlowFullScreen;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable logoName;)
+ (NSString * _Nullable)logoName SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogoName:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable companyLogoName;)
+ (NSString * _Nullable)companyLogoName SWIFT_WARN_UNUSED_RESULT;
+ (void)setCompanyLogoName:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable mainBackgroundName;)
+ (NSString * _Nullable)mainBackgroundName SWIFT_WARN_UNUSED_RESULT;
+ (void)setMainBackgroundName:(NSString * _Nullable)value;
+ (void)invokeTheme:(id <FTSDKTheme> _Nonnull)theme;
+ (void)setDebug:(BOOL)isDebug;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKDeviceUtils")
@interface FTSDKDeviceUtils : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable bundleName;)
+ (NSString * _Nullable)bundleName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable systemVersion;)
+ (NSString * _Nullable)systemVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceModel;)
+ (NSString * _Nonnull)deviceModel SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable deviceId;)
+ (NSString * _Nullable)deviceId SWIFT_WARN_UNUSED_RESULT;
+ (void)setDeviceId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceOs;)
+ (NSString * _Nonnull)deviceOs SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable deviceName;)
+ (NSString * _Nullable)deviceName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getDeviceInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getExtraData SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull mobileCarrier;)
+ (NSString * _Nonnull)mobileCarrier SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull modelName;)
+ (NSString * _Nonnull)modelName SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull deviceIPv4;)
+ (NSString * _Nonnull)deviceIPv4 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;
enum ActionStyle : NSInteger;

SWIFT_CLASS("_TtC12FTSDKCoreKit17FTSDKDialogAction")
@interface FTSDKDialogAction : NSObject
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title image:(UIImage * _Nullable)image style:(enum ActionStyle)style handler:(void (^ _Nullable)(void))handler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title style:(enum ActionStyle)style handler:(void (^ _Nullable)(void))handler OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ActionStyle, open) {
  ActionStyleDefault = 0,
  ActionStyleCancel = 1,
  ActionStyleDestructive = 2,
};


SWIFT_CLASS("_TtC12FTSDKCoreKit21FTSDKDialogController")
@interface FTSDKDialogController : NSObject
- (void)showWithCompletion:(void (^ _Nullable)(void))completion;
- (void)hide;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit30FTSDKDynamicLinkObjectProtocol_")
@protocol FTSDKDynamicLinkObjectProtocol
@property (nonatomic, readonly, copy) NSURL * _Nullable url;
@property (nonatomic, readonly, copy) NSDictionary * _Nullable payload;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit22FTSDKDynamicLinkObject")
@interface FTSDKDynamicLinkObject : NSObject <FTSDKDynamicLinkObjectProtocol>
@property (nonatomic, copy) NSURL * _Nullable url;
@property (nonatomic, copy) NSDictionary * _Nullable payload;
- (nonnull instancetype)init:(NSURL * _Nullable)url payload:(NSDictionary * _Nullable)payload OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP12FTSDKCoreKit24FTSDKDynamicLinkProtocol_")
@protocol FTSDKDynamicLinkProtocol
- (BOOL)handleUniversalLink:(NSURL * _Nonnull)url handler:(void (^ _Nonnull)(id <FTSDKDynamicLinkObjectProtocol> _Nonnull))handler;
- (BOOL)handleDynamicLinkFromSchemeURL:(NSURL * _Nonnull)schemeUrl handler:(void (^ _Nonnull)(id <FTSDKDynamicLinkObjectProtocol> _Nonnull))handler;
@optional
- (void)configure;
- (void)start;
@end

@protocol FTSDKDynamicLinksDelegate;

SWIFT_CLASS("_TtC12FTSDKCoreKit17FTSDKDynamicLinks")
@interface FTSDKDynamicLinks : NSObject
+ (FTSDKDynamicLinks * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <FTSDKDynamicLinksDelegate> _Nullable delegate;
- (void)addDynamicLink:(id <FTSDKDynamicLinkProtocol> _Nonnull)dynamicLink;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit25FTSDKDynamicLinksDelegate_")
@protocol FTSDKDynamicLinksDelegate
@optional
- (void)dynamicLinksWithDidReceiveWithObject:(id <FTSDKDynamicLinkObjectProtocol> _Nonnull)dynamicLinkObj;
@end

typedef SWIFT_ENUM(NSInteger, FTSDKEnvironment, open) {
  FTSDKEnvironmentPro = 0,
  FTSDKEnvironmentDev = 1,
};


SWIFT_CLASS("_TtC12FTSDKCoreKit10FTSDKError")
@interface FTSDKError : NSError
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger PURCHASE_PEINDING;)
+ (NSInteger)PURCHASE_PEINDING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger PROVIDER_3RD_NOTFOUND;)
+ (NSInteger)PROVIDER_3RD_NOTFOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUTH_3RD_NOTFOUND_TOKEN;)
+ (NSInteger)AUTH_3RD_NOTFOUND_TOKEN SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWith:(NSError * _Nonnull)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCode:(NSInteger)code message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)jsonDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)base64Description SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

@class UIViewController;
@class NSBundle;
@protocol UIViewControllerAnimatedTransitioning;

SWIFT_CLASS("_TtC12FTSDKCoreKit29FTSDKFadeNavigationController")
@interface FTSDKFadeNavigationController : UINavigationController <UINavigationControllerDelegate>
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
- (void)viewDidLoad;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)navigationController:(UINavigationController * _Nonnull)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController * _Nonnull)fromVC toViewController:(UIViewController * _Nonnull)toVC SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, FTSDKFlow, open) {
  FTSDKFlowFullscreen = 0,
  FTSDKFlowDialog = 1,
};

@protocol FTSDKFormFieldDelegate;
@class NSItemProvider;
@class UIPasteConfiguration;

SWIFT_CLASS("_TtC12FTSDKCoreKit14FTSDKFormField")
@interface FTSDKFormField : UIView
@property (nonatomic, weak) IBOutlet id <FTSDKFormFieldDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) IBInspectable NSInteger maxLength;
@property (nonatomic) IBInspectable CGFloat textFieldHeight;
@property (nonatomic, readonly, strong) IBInspectable UIColor * _Nullable textFieldBorderColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable textFieldBackgroundColor;
@property (nonatomic, copy) IBInspectable NSString * _Nullable text;
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic, copy) IBInspectable NSString * _Nullable message;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
@property (nonatomic) IBInspectable BOOL clearsOnBeginEditing;
@property (nonatomic) IBInspectable BOOL adjustsFontSizeToFitWidth;
@property (nonatomic) IBInspectable BOOL allowsEditingTextAttributes;
@property (nonatomic) UIKeyboardType keyboardType;
- (BOOL)canPasteItemProviders:(NSArray<NSItemProvider *> * _Nonnull)itemProviders SWIFT_WARN_UNUSED_RESULT;
- (void)paste:(id _Nullable)sender;
@property (nonatomic, strong) UIPasteConfiguration * _Nullable pasteConfiguration;
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
@property (nonatomic, readonly) BOOL canResignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic, strong) UIView * _Nullable inputView;
@property (nonatomic, strong) UIView * _Nullable inputAccessoryView;
@property (nonatomic, copy) IBInspectable NSString * _Nullable leftText;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftImage;
@property (nonatomic, copy) IBInspectable NSString * _Nullable rightText;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable rightImage;
@end



@interface FTSDKFormField (SWIFT_EXTENSION(FTSDKCoreKit)) <UIContentSizeCategoryAdjusting>
@property (nonatomic) BOOL adjustsFontForContentSizeCategory;
@end


@protocol UITextDragDelegate;
@class UIDragInteraction;
@protocol UITextDropDelegate;
@class UIDropInteraction;
@protocol UITextPasteDelegate;

@interface FTSDKFormField (SWIFT_EXTENSION(FTSDKCoreKit)) <UITextDraggable, UITextDroppable>
@property (nonatomic, strong) id <UITextDragDelegate> _Nullable textDragDelegate;
@property (nonatomic, readonly, strong) UIDragInteraction * _Nullable textDragInteraction;
@property (nonatomic, readonly, getter=isTextDragActive) BOOL textDragActive;
@property (nonatomic) UITextDragOptions textDragOptions;
@property (nonatomic, strong) id <UITextDropDelegate> _Nullable textDropDelegate;
@property (nonatomic, readonly, strong) UIDropInteraction * _Nullable textDropInteraction;
@property (nonatomic, readonly, getter=isTextDropActive) BOOL textDropActive;
@property (nonatomic, strong) id <UITextPasteDelegate> _Nullable pasteDelegate;
@end

@class UITextRange;
@class UITextPosition;
@protocol UITextInputDelegate;
@protocol UITextInputTokenizer;
@class UITextSelectionRect;

@interface FTSDKFormField (SWIFT_EXTENSION(FTSDKCoreKit)) <UITextInput>
- (void)replaceRange:(UITextRange * _Nonnull)range withText:(NSString * _Nonnull)text;
@property (nonatomic, strong) UITextRange * _Nullable selectedTextRange;
@property (nonatomic, readonly, strong) UITextRange * _Nullable markedTextRange;
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nullable markedTextStyle;
- (void)setMarkedText:(NSString * _Nullable)markedText selectedRange:(NSRange)selectedRange;
- (void)unmarkText;
@property (nonatomic, readonly, strong) UITextPosition * _Nonnull beginningOfDocument;
@property (nonatomic, readonly, strong) UITextPosition * _Nonnull endOfDocument;
- (UITextRange * _Nullable)textRangeFromPosition:(UITextPosition * _Nonnull)fromPosition toPosition:(UITextPosition * _Nonnull)toPosition SWIFT_WARN_UNUSED_RESULT;
- (UITextPosition * _Nullable)positionFromPosition:(UITextPosition * _Nonnull)position offset:(NSInteger)offset SWIFT_WARN_UNUSED_RESULT;
- (UITextPosition * _Nullable)positionFromPosition:(UITextPosition * _Nonnull)position inDirection:(UITextLayoutDirection)direction offset:(NSInteger)offset SWIFT_WARN_UNUSED_RESULT;
- (NSComparisonResult)comparePosition:(UITextPosition * _Nonnull)position toPosition:(UITextPosition * _Nonnull)other SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)offsetFromPosition:(UITextPosition * _Nonnull)from toPosition:(UITextPosition * _Nonnull)toPosition SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) id <UITextInputDelegate> _Nullable inputDelegate;
@property (nonatomic, readonly, strong) id <UITextInputTokenizer> _Nonnull tokenizer;
- (UITextPosition * _Nullable)positionWithinRange:(UITextRange * _Nonnull)range farthestInDirection:(UITextLayoutDirection)direction SWIFT_WARN_UNUSED_RESULT;
- (UITextRange * _Nullable)characterRangeByExtendingPosition:(UITextPosition * _Nonnull)position inDirection:(UITextLayoutDirection)direction SWIFT_WARN_UNUSED_RESULT;
- (NSWritingDirection)baseWritingDirectionForPosition:(UITextPosition * _Nonnull)position inDirection:(UITextStorageDirection)direction SWIFT_WARN_UNUSED_RESULT;
- (void)setBaseWritingDirection:(NSWritingDirection)writingDirection forRange:(UITextRange * _Nonnull)range;
- (CGRect)firstRectForRange:(UITextRange * _Nonnull)range SWIFT_WARN_UNUSED_RESULT;
- (CGRect)caretRectForPosition:(UITextPosition * _Nonnull)position SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UITextSelectionRect *> * _Nonnull)selectionRectsForRange:(UITextRange * _Nonnull)range SWIFT_WARN_UNUSED_RESULT;
- (UITextPosition * _Nullable)closestPositionToPoint:(CGPoint)point SWIFT_WARN_UNUSED_RESULT;
- (UITextPosition * _Nullable)closestPositionToPoint:(CGPoint)point withinRange:(UITextRange * _Nonnull)range SWIFT_WARN_UNUSED_RESULT;
- (UITextRange * _Nullable)characterRangeAtPoint:(CGPoint)point SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)textInRange:(UITextRange * _Nonnull)range SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL hasText;
- (void)insertText:(NSString * _Nonnull)text;
- (void)deleteBackward;
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit22FTSDKFormFieldDelegate_")
@protocol FTSDKFormFieldDelegate
@optional
- (void)formFieldDidTapLeftView:(FTSDKFormField * _Nonnull)formField;
- (void)formFieldDidTapRightView:(FTSDKFormField * _Nonnull)formField;
- (void)formFieldTouchesBeganRightView:(FTSDKFormField * _Nonnull)formField;
- (void)formFieldTouchesEndRightView:(FTSDKFormField * _Nonnull)formField;
- (BOOL)formFieldShouldBeginEditing:(FTSDKFormField * _Nonnull)formField SWIFT_WARN_UNUSED_RESULT;
- (void)formFieldDidBeginEditing:(FTSDKFormField * _Nonnull)formField;
- (BOOL)formFieldShouldEndEditing:(FTSDKFormField * _Nonnull)formField SWIFT_WARN_UNUSED_RESULT;
- (void)formFieldDidEndEditing:(FTSDKFormField * _Nonnull)formField;
- (void)formFieldDidEndEditing:(FTSDKFormField * _Nonnull)formField reason:(UITextFieldDidEndEditingReason)reason;
- (BOOL)formField:(FTSDKFormField * _Nonnull)formField shouldChangeCharactersIn:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (void)formFieldDidChangeSelection:(FTSDKFormField * _Nonnull)formField SWIFT_AVAILABILITY(ios,introduced=13.0);
- (BOOL)formFieldShouldClear:(FTSDKFormField * _Nonnull)formField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)formFieldShouldReturn:(FTSDKFormField * _Nonnull)formField SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit19FTSDKFunzyOrderInfo")
@interface FTSDKFunzyOrderInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull cooOrderSerial;
- (nonnull instancetype)initWithCooOrderSerial:(NSString * _Nonnull)cooOrderSerial OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit17FTSDKGalleryPhoto")
@interface FTSDKGalleryPhoto : NSObject
@property (nonatomic, readonly, strong) UIImage * _Nonnull image;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
- (nonnull instancetype)initWithImage:(UIImage * _Nonnull)image name:(NSString * _Nullable)name type:(NSString * _Nullable)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit27FTSDKGalleryServiceProtocol_")
@protocol FTSDKGalleryServiceProtocol
@property (nonatomic, copy) void (^ _Nullable imagePickedListener)(FTSDKGalleryPhoto * _Nonnull);
- (void)showPickerWithOptions:(UIViewController * _Nullable)context;
- (void)showPickerWithOptions:(UIViewController * _Nullable)context allowsEditing:(BOOL)allowsEditing;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit27FTSDKHeaderDialogController")
@interface FTSDKHeaderDialogController : NSObject
+ (void)showMessageWithMessage:(NSString * _Nullable)message duration:(NSTimeInterval)duration color:(UIColor * _Nullable)color textColor:(UIColor * _Nonnull)textColor iconImage:(UIImage * _Nullable)iconImage;
+ (void)hideMessageWithAnimation:(BOOL)animation;
+ (void)showSuccessWithMessage:(NSString * _Nullable)message duration:(NSTimeInterval)duration;
+ (void)showErrorWithMessage:(NSString * _Nullable)message duration:(NSTimeInterval)duration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit14FTSDKIAPHelper")
@interface FTSDKIAPHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class SKProductsRequest;
@class SKProductsResponse;
@class SKRequest;

@interface FTSDKIAPHelper (SWIFT_EXTENSION(FTSDKCoreKit)) <SKProductsRequestDelegate>
- (void)productsRequest:(SKProductsRequest * _Nonnull)request didReceiveResponse:(SKProductsResponse * _Nonnull)response;
- (void)request:(SKRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end



@class SKPaymentQueue;
@class SKPaymentTransaction;

@interface FTSDKIAPHelper (SWIFT_EXTENSION(FTSDKCoreKit)) <SKPaymentTransactionObserver>
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue updatedTransactions:(NSArray<SKPaymentTransaction *> * _Nonnull)transactions;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue * _Nonnull)queue;
- (void)paymentQueue:(SKPaymentQueue * _Nonnull)queue restoreCompletedTransactionsFailedWithError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit18FTSDKIndicatorView")
@interface FTSDKIndicatorView : UIView
@property (nonatomic, readonly) CGSize intrinsicContentSize;
@property (nonatomic) CGRect bounds;
/// Color of activity indicator view.
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull color;
/// Padding of activity indicator view.
@property (nonatomic) IBInspectable CGFloat padding;
@property (nonatomic) IBInspectable CGFloat lineWidth;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit18FTSDKInfrasFactory")
@interface FTSDKInfrasFactory : NSObject
+ (id <FTSDKGalleryServiceProtocol> _Nonnull)getGalleryService SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit20FTSDKKeychainService")
@interface FTSDKKeychainService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, FTSDKLanguage, open) {
  FTSDKLanguageVietnamese = 0,
  FTSDKLanguageEnglish = 1,
};


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit24FTSDKLinkAccountDelegate_")
@protocol FTSDKLinkAccountDelegate
@optional
- (void)didLinkAccountSuccessWithUser:(FTSDKUser * _Nonnull)user;
- (void)didLinkAccountFailWithError:(FTSDKError * _Nonnull)error;
@end

@class FTSDKPackageData;

SWIFT_CLASS("_TtC12FTSDKCoreKit20FTSDKListPackageData")
@interface FTSDKListPackageData : NSObject
@property (nonatomic, copy) NSArray<FTSDKPackageData *> * _Nullable packages;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit22FTSDKListSelectionView")
@interface FTSDKListSelectionView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit28FTSDKLoadingDialogController")
@interface FTSDKLoadingDialogController : NSObject
+ (void)showWithTitle:(NSString * _Nonnull)title;
+ (void)hideWithAnimation:(BOOL)animation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKLoadingView")
@interface FTSDKLoadingView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit22FTSDKNavigationBarView")
@interface FTSDKNavigationBarView : UIView
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The (blurred) overlay view below the popup dialog
SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKOverlayView")
@interface FTSDKOverlayView : UIView
/// The background color of the overlay view
@property (nonatomic, strong) UIColor * _Nullable color;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKPackageData")
@interface FTSDKPackageData : NSObject
@property (nonatomic, copy) NSString * _Nullable gameCode;
@property (nonatomic, copy) NSString * _Nullable osType;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable packageName;
@property (nonatomic, copy) NSString * _Nullable packageDetail;
@property (nonatomic, copy) NSString * _Nullable inGamePackageId;
@property (nonatomic, copy) NSString * _Nullable storePackageId;
@property (nonatomic, copy) NSString * _Nullable displayCurrency;
- (NSNumber * _Nonnull)getAmount SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)listJSON:(NSArray<FTSDKPackageData *> * _Nonnull)list SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit15FTSDKPlayerInfo")
@interface FTSDKPlayerInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull accountName;
@property (nonatomic, copy) NSString * _Nonnull portalCode;
@property (nonatomic, copy) NSString * _Nonnull gameCode;
@property (nonatomic, copy) NSString * _Nonnull gameServer;
@property (nonatomic, copy) NSString * _Nonnull nickName;
- (nonnull instancetype)initWithGameServer:(NSString * _Nonnull)gameServer nickName:(NSString * _Nonnull)nickName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIPresentationController;

SWIFT_CLASS("_TtC12FTSDKCoreKit24FTSDKPresentationManager")
@interface FTSDKPresentationManager : NSObject <UIViewControllerTransitioningDelegate>
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKProfileData")
@interface FTSDKProfileData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable sub;
@property (nonatomic, readonly, copy) NSString * _Nullable picture;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
@property (nonatomic, readonly, copy) NSString * _Nullable phoneNumber;
@property (nonatomic, readonly, copy) NSString * _Nullable preferredUsername;
@property (nonatomic, readonly, copy) NSString * _Nullable additionalInfo;
@property (nonatomic, readonly) BOOL ekycVerified;
@property (nonatomic, readonly, strong) FTSDKCardData * _Nullable cardInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol FTSDKPurchaseDelegate;
@class FTSDKTransaction;

SWIFT_CLASS("_TtC12FTSDKCoreKit13FTSDKPurchase")
@interface FTSDKPurchase : NSObject
@property (nonatomic, weak) id <FTSDKPurchaseDelegate> _Nullable delegate;
@property (nonatomic) BOOL isDebug;
+ (FTSDKPurchase * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
- (void)setPlayerInfoWithGameServer:(NSString * _Nonnull)gameServer nickName:(NSString * _Nonnull)nickName;
- (void)createLogGameWithGameServer:(NSString * _Nonnull)gameServer nickName:(NSString * _Nonnull)nickName gameCode:(NSString * _Nonnull)gameCode;
- (void)getListPackagesOnSuccess:(void (^ _Nonnull)(FTSDKListPackageData * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(FTSDKError * _Nonnull))onFailure;
- (void)paymentWithUISDKWithFunzyOrderInfo:(FTSDKFunzyOrderInfo * _Nonnull)funzyOrderInfo;
- (void)paymentWithoutUISDKWith:(FTSDKPackageData * _Nonnull)package funzyOrderInfo:(FTSDKFunzyOrderInfo * _Nonnull)funzyOrderInfo;
- (void)reVerifyPendingTransacionsWithCompleted:(void (^ _Nullable)(NSArray<FTSDKTransaction *> * _Nonnull))completed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP12FTSDKCoreKit21FTSDKPurchaseDelegate_")
@protocol FTSDKPurchaseDelegate
- (void)didPurchaseSuccessWithTransacion:(FTSDKTransaction * _Nonnull)transacion;
- (void)didPurchaseFailedWithError:(FTSDKError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit7FTSDKQA")
@interface FTSDKQA : NSObject
+ (void)startShowQA;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit11FTSDKSignIn")
@interface FTSDKSignIn : NSObject
@property (nonatomic, weak) id <FTSDKAuthDelegate> _Nullable delegate;
@property (nonatomic, weak) id <FTSDKLinkAccountDelegate> _Nullable linkAccountDelegate;
@property (nonatomic, readonly) BOOL isLoginFID;
+ (FTSDKSignIn * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
- (void)signIn;
- (void)linkAccount;
- (void)signOutWithCompleted:(void (^ _Nullable)(FTSDKError * _Nullable))completed;
- (void)changePasswordWithCompleted:(void (^ _Nullable)(void))completed;
- (void)updatePhoneFor3rd;
- (void)getUserInfoWith:(BOOL)loading onSuccess:(void (^ _Nonnull)(FTSDKUser * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(FTSDKError * _Nonnull))onFailure;
- (void)refreshTokenOnSuccess:(void (^ _Nonnull)(FTSDKAuthentication * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(FTSDKError * _Nonnull))onFailure;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



@class NSTextContainer;

SWIFT_CLASS("_TtC12FTSDKCoreKit13FTSDKTextView")
@interface FTSDKTextView : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit10FTSDKTheme_")
@protocol FTSDKTheme
@property (nonatomic, copy) NSString * _Nonnull mainColor;
@property (nonatomic, copy) NSString * _Nonnull mainGradientStartColor;
@property (nonatomic, copy) NSString * _Nonnull mainGradientEndColor;
@property (nonatomic, copy) NSString * _Nonnull mainBackgroundColor;
@property (nonatomic, copy) NSString * _Nonnull textPrimaryColor;
@property (nonatomic, copy) NSString * _Nonnull textPrimarySecondaryColor;
@property (nonatomic, copy) NSString * _Nonnull textHintColor;
@property (nonatomic, copy) NSString * _Nonnull textLinkColor;
@property (nonatomic, copy) NSString * _Nonnull textBoxBorderColor;
@property (nonatomic, copy) NSString * _Nonnull buttonBackgroundDisableColor;
@property (nonatomic, copy) NSString * _Nonnull buttonBackgroundEnableColor;
@property (nonatomic, copy) NSString * _Nonnull buttonBorderColor;
@property (nonatomic, copy) NSString * _Nonnull buttonTextColor;
@property (nonatomic, copy) NSString * _Nonnull buttonTextDisableColor;
@property (nonatomic, copy) NSString * _Nonnull buttonTextEnableColor;
@property (nonatomic, copy) NSString * _Nonnull validMessageLabelColor;
@property (nonatomic, copy) NSString * _Nonnull inValidMessageLabelColor;
@property (nonatomic, copy) NSString * _Nonnull checkedBoxColor;
@property (nonatomic, copy) NSString * _Nonnull timeRemainLabel;
@property (nonatomic, copy) NSString * _Nonnull secondRemainLabel;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12FTSDKToolbar")
@interface FTSDKToolbar : UIToolbar <UIInputViewAudioFeedback>
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
@property (nonatomic, readonly) BOOL enableInputClicksWhenVisible;
@end


SWIFT_PROTOCOL("_TtP12FTSDKCoreKit20FTSDKTrackerProtocol_")
@protocol FTSDKTrackerProtocol
@property (nonatomic) BOOL isEnableDebug;
- (void)trackEvent:(NSString * _Nonnull)event :(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)trackEvent:(NSString * _Nonnull)event;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit13FTSDKTracking")
@interface FTSDKTracking : NSObject
+ (FTSDKTracking * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) id <FTSDKTrackerProtocol> _Nonnull tracker;
@property (nonatomic) BOOL isDebug;
+ (void)configure;
+ (NSDictionary<NSString *, id> * _Nonnull)getDefaultParams SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)buildName:(NSString * _Nonnull)name from:(NSString * _Nonnull)oldPrefix to:(NSString * _Nonnull)newPrefix SWIFT_WARN_UNUSED_RESULT;
- (void)logEvent:(NSString * _Nonnull)event params:(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)logEvent:(NSString * _Nonnull)event;
- (void)addTracker:(id <FTSDKTrackerProtocol> _Nonnull)tracker;
- (void)requestTrackingAuthorization;
- (void)onConversionDataSuccess:(NSDictionary * _Nonnull)data;
- (void)onConversionDataFail:(NSError * _Nonnull)error;
/// // Defaults to None which doesn’t get serialized
/// kSentryLevelNone = 0,
/// // Goes from Debug to Fatal so possible to: (level > Info) { .. }
/// kSentryLevelDebug = 1,
/// kSentryLevelInfo = 2,
/// kSentryLevelWarning = 3,
/// kSentryLevelError = 4,
/// kSentryLevelFatal = 5
+ (void)addBreadcrumbWithLevel:(NSInteger)level category:(NSString * _Nonnull)category message:(NSString * _Nonnull)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16FTSDKTransaction")
@interface FTSDKTransaction : NSObject
@property (nonatomic, copy) NSString * _Nonnull transId;
- (nonnull instancetype)initWithTransId:(NSString * _Nonnull)transId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("FTSDKTransactionEntity")
@interface FTSDKTransactionEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface FTSDKTransactionEntity (SWIFT_EXTENSION(FTSDKCoreKit))
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable customerId;
@property (nonatomic, copy) NSString * _Nullable storePackageId;
@property (nonatomic, copy) NSString * _Nullable extraData;
@property (nonatomic, copy) NSString * _Nullable appleBundleCode;
@property (nonatomic, copy) NSString * _Nullable appleReceiptDataEncoded;
@property (nonatomic) int16_t appleSkPaymentTransactionState;
@property (nonatomic, copy) NSString * _Nullable appleOrderId;
@property (nonatomic, copy) NSString * _Nullable funzyOrderId;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable deviceIPv4;
@property (nonatomic, copy) NSString * _Nullable deviceProductName;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit9FTSDKUser")
@interface FTSDKUser : NSObject
@property (nonatomic, strong) FTSDKProfileData * _Nonnull profile;
@property (nonatomic, readonly, strong) FTSDKAuthentication * _Nonnull authentication;
@property (nonatomic, readonly) BOOL isValid;
@property (nonatomic, readonly) BOOL isJustSignUp;
- (nonnull instancetype)init:(FTSDKProfileData * _Nonnull)profile :(FTSDKAuthentication * _Nonnull)authen OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)jsonDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)base64Description SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12FTSDKXibView")
@interface FTSDKXibView : UIView
@property (nonatomic, readonly, copy) NSString * _Nonnull nibName;
@property (nonatomic, readonly, strong) UIView * _Nonnull containerView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)configViews;
- (void)loadViews;
- (NSBundle * _Nonnull)bundleView SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit17GetConfigResponse")
@interface GetConfigResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSAttributedString;

SWIFT_CLASS("_TtC12FTSDKCoreKit19GradientColorButton")
@interface GradientColorButton : UIButton
- (void)layoutSubviews;
@property (nonatomic, getter=isEnabled) BOOL enabled;
- (void)setAttributedTitle:(NSAttributedString * _Nullable)title forState:(UIControlState)state;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12FTSDKCoreKit10IapConfigs")
@interface IapConfigs : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12FTSDKCoreKit18MaintenanceConfigs")
@interface MaintenanceConfigs : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12ModuleConfig")
@interface ModuleConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






SWIFT_CLASS("_TtC12FTSDKCoreKit20NoSelectionTextField")
@interface NoSelectionTextField : CustomTextField
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12OtherConfigs")
@interface OtherConfigs : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit20PhoneNumberTextField")
@interface PhoneNumberTextField : NoSelectionTextField <UITextFieldDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)textFieldDidChange:(PhoneNumberTextField * _Nullable)textField;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldEndEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit16QAViewController")
@interface QAViewController : UIViewController
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class WKUserContentController;
@class WKScriptMessage;

@interface QAViewController (SWIFT_EXTENSION(FTSDKCoreKit)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKWebView;
@class WKNavigation;

@interface QAViewController (SWIFT_EXTENSION(FTSDKCoreKit)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12SDKPromotion")
@interface SDKPromotion : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable image;
@property (nonatomic, readonly, copy) NSString * _Nullable imageLanscape;
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit11SDKSettings")
@interface SDKSettings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12FTSDKCoreKit10ThemeColor")
@interface ThemeColor : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit12ThemeConfigs")
@interface ThemeConfigs : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12FTSDKCoreKit11ThemeImages")
@interface ThemeImages : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

















@interface UIScrollView (SWIFT_EXTENSION(FTSDKCoreKit)) <UIGestureRecognizerDelegate>
@end




















#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
